$(document).ready(function(){
    $("#dev_icon").click(function(){
      $("#dev_icon").slideDown('1500').hide('1000');
      $("#development").show('1500');
    });
    $("#development").click(function(){
      $("#development").slideUp('1500');
      $("#dev_icon").slideDown('1500');
    });
  });
  $(document).ready(function(){
    $("#design-icon").click(function(){
      $("#design-icon").slideDown('1500').hide('1000');
      $("#design").show('1500');
    });
    $("#design").click(function(){
      $("#design").slideUp('1500');
      $("#design-icon").slideDown('1500');
    });
  });
  $(document).ready(function(){
    $("#product_icon").click(function(){
      $("#product_icon").slideDown('1500').hide('1000');
      $("#product").show('1500');
    });
    $("#product").click(function(){
      $("#product").slideUp('1500');
      $("#product_icon").slideDown('1500');
    });
  });